import type { SavedWord } from './types';

export const CURATED_WORDS: SavedWord[] = [
  {
    id: 'cw_1',
    word: 'ephemeral',
    query: 'ephemeral',
    definition: 'lasting for a very short time.',
    phonetic: 'ɪˈfɛmərəl',
    partOfSpeech: 'adjective',
    example: 'fashions are ephemeral',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_2',
    word: 'mellifluous',
    query: 'mellifluous',
    definition: '(of a voice or words) sweet or musical; pleasant to hear.',
    phonetic: 'mɛˈlɪflʊəs',
    partOfSpeech: 'adjective',
    example: 'the voice was mellifluous and smooth',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_3',
    word: 'petrichor',
    query: 'petrichor',
    definition: 'a pleasant smell that frequently accompanies the first rain after a long period of warm, dry weather.',
    phonetic: 'ˈpɛtrɪkɔː',
    partOfSpeech: 'noun',
    example: 'other than the petrichor emanating from the rapidly drying grass, there was not a trace of evidence that it had rained at all',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_4',
    word: 'sonder',
    query: 'sonder',
    definition: 'the realization that each random passerby has a life as vivid and complex as your own.',
    phonetic: 'ˈsɒndə',
    partOfSpeech: 'noun',
    example: 'she experienced a profound sense of sonder while watching the crowds at the station',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_5',
    word: 'liminal',
    query: 'liminal',
    definition: 'occupying a position at, or on both sides of, a boundary or threshold.',
    phonetic: 'ˈlɪmɪn(ə)l',
    partOfSpeech: 'adjective',
    example: 'the liminal state between waking and sleeping',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_6',
    word: 'serendipity',
    query: 'serendipity',
    definition: 'the occurrence and development of events by chance in a happy or beneficial way.',
    phonetic: 'ˌsɛr(ə)nˈdɪpɪti',
    partOfSpeech: 'noun',
    example: 'a fortunate stroke of serendipity',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_7',
    word: 'luminous',
    query: 'luminous',
    definition: 'full of or shedding light; bright or shining, especially in the dark.',
    phonetic: 'ˈluːmɪnəs',
    partOfSpeech: 'adjective',
    example: 'the luminous dial on his watch',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_8',
    word: 'susurrus',
    query: 'susurrus',
    definition: 'whispering, murmuring, or rustling.',
    phonetic: 'sʊˈsʌrəs',
    partOfSpeech: 'noun',
    example: 'the susurrus of the stream',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_9',
    word: 'eloquence',
    query: 'eloquence',
    definition: 'fluent or persuasive speaking or writing.',
    phonetic: 'ˈɛləkwəns',
    partOfSpeech: 'noun',
    example: 'a preacher of great power and eloquence',
    source: 'offline',
    savedAt: 0,
  },
  {
    id: 'cw_10',
    word: 'soliloquy',
    query: 'soliloquy',
    definition: 'an act of speaking one\'s thoughts aloud when by oneself or regardless of any hearers.',
    phonetic: 'səˈlɪləkwi',
    partOfSpeech: 'noun',
    example: 'in the opening soliloquy he declares his true intent',
    source: 'offline',
    savedAt: 0,
  },
];
